In [78]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

import statsmodels.api as sm
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_auc_score

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [37]:
data = pd.read_csv('dataset-66223.csv')

le = LabelEncoder()
data['Purchase'] = le.fit_transform(data['Purchase'])

In [38]:
test = data.iloc[:1000,:]
train = data.iloc[1000:,:]

In [39]:
X_train = train.iloc[:,:-1]
y_train = train.iloc[:,-1]

X_test = test.iloc[:,:-1]
y_test = test.iloc[:,-1]

In [50]:
X_train

MOSTYPE  MAANTHUI  MGEMOMV  MGEMLEEF  MOSHOOFD  MGODRK  MGODPR  MGODOV  \
1000       40         1        5         3        10       1       1       5   
1001       26         1        1         5         6       0       4       2   
1002       10         1        4         2         3       2       6       0   
1003       38         1        2         2         9       0       4       2   
1004       39         2        3         3         9       1       5       0   
...       ...       ...      ...       ...       ...     ...     ...     ...   
5817       36         1        1         2         8       0       6       1   
5818       35         1        4         4         8       1       4       1   
5819       33         1        3         4         8       0       6       0   
5820       34         1        3         2         8       0       7       0   
5821       33         1        3         3         8       0       6       1   

      MGODGE  MRELGE  ...  ALEVEN  APERSONG  AGEZONG  AWAOREG  ABRAND  \
1000       3       9  ...       0         0        0        0       1   
1001       4       3  ...       0         0        0        0       1   
1002       3       6  ...       0         0        0        0       0   
1003       4       7  ...       0         0        0        0       0   
1004       3       7  ...       0         0        0        0       0   
...      ...     ...  ...     ...       ...      ...      ...     ...   
5817       2       1  ...       2         0        0        0       1   
5818       4       6  ...       0         0        0        0       1   
5819       3       5  ...       0         0        0        0       1   
5820       2       7  ...       0         0        0        0       0   
5821       2       7  ...       0         0        0        0       0   

      AZEILPL  APLEZIER  AFIETS  AINBOED  ABYSTAND  
1000        0         0       0        0         0  
1001        0         0       0        0         0  
1002        0         0       0        0         0  
1003        0         0       0        0         0  
1004        0         0       0        0         0  
...       ...       ...     ...      ...       ...  
5817        0         0       0        0         0  
5818        0         0       0        0         0  
5819        0         0       0        0         0  
5820        0         0       0        0         0  
5821        0         0       0        0         0  

[4822 rows x 85 columns]

In [70]:
#logreg = LogisticRegression(penalty = 'none', fit_intercept=False)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/Users/wenbofu/miniforge3/envs/torch_m1/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [71]:
y_prob = logreg.predict_proba(X_test)[:, 1]

In [72]:
cutoff = 0.25
y_pred = (y_prob >= cutoff).astype(int)

In [73]:
conf_matrix = confusion_matrix(y_test, y_pred)

In [74]:
conf_matrix

array([[922,  19],
       [ 50,   9]])

In [59]:
auc = roc_auc_score(y_test, y_prob)

In [60]:
auc

0.750310704443524

In [61]:
model = sm.GLM(y_train, X_train, family = sm.families.Binomial()).fit()

In [64]:
confusion_matrix(y_test, model.predict(X_test)>0.25)

array([[919,  22],
       [ 48,  11]])

In [75]:
roc_auc_score(y_test, model.predict(X_test))

0.739287451142852

In [76]:
y_test

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: Purchase, Length: 1000, dtype: int64

In [77]:
model.predict(X_test)

0      0.092121
1      0.009769
2      0.056163
3      0.087468
4      0.027484
         ...   
995    0.106100
996    0.215950
997    0.019345
998    0.161420
999    0.030191
Length: 1000, dtype: float64

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, roc_auc_score

import numpy as np

import statsmodels.api as sm
import statsmodels.formula.api as smf

In [4]:
data

MOSTYPE  MAANTHUI  MGEMOMV  MGEMLEEF  MOSHOOFD  MGODRK  MGODPR  MGODOV  \
0          33         1        3         2         8       0       5       1   
1          37         1        2         2         8       1       4       1   
2          37         1        2         2         8       0       4       2   
3           9         1        3         3         3       2       3       2   
4          40         1        4         2        10       1       4       1   
...       ...       ...      ...       ...       ...     ...     ...     ...   
5817       36         1        1         2         8       0       6       1   
5818       35         1        4         4         8       1       4       1   
5819       33         1        3         4         8       0       6       0   
5820       34         1        3         2         8       0       7       0   
5821       33         1        3         3         8       0       6       1   

      MGODGE  MRELGE  ...  APERSONG  AGEZONG  AWAOREG  ABRAND  AZEILPL  \
0          3       7  ...         0        0        0       1        0   
1          4       6  ...         0        0        0       1        0   
2          4       3  ...         0        0        0       1        0   
3          4       5  ...         0        0        0       1        0   
4          4       7  ...         0        0        0       1        0   
...      ...     ...  ...       ...      ...      ...     ...      ...   
5817       2       1  ...         0        0        0       1        0   
5818       4       6  ...         0        0        0       1        0   
5819       3       5  ...         0        0        0       1        0   
5820       2       7  ...         0        0        0       0        0   
5821       2       7  ...         0        0        0       0        0   

      APLEZIER  AFIETS  AINBOED  ABYSTAND  Y  
0            0       0        0         0  0  
1            0       0        0         0  0  
2            0       0        0         0  0  
3            0       0        0         0  0  
4            0       0        0         0  0  
...        ...     ...      ...       ... ..  
5817         0       0        0         0  0  
5818         0       0        0         0  0  
5819         0       0        0         0  1  
5820         0       0        0         0  0  
5821         0       0        0         0  0  

[5822 rows x 86 columns]

In [2]:
# Load the dataset
url = "https://liangfgithub.github.io/Data/Caravan.csv"
data = pd.read_csv(url)

# Rename the last column to "Y"
data.rename(columns={data.columns[-1]: "Y"}, inplace=True)

# Convert "Y" column to binary values (1 for "Yes", 0 for "No")
data['Y'] = data['Y'].apply(lambda x: 1 if x == "Yes" else 0)

# Convert "Y" column to a factor
data['Y'] = pd.Categorical(data['Y'])


# Split data into train and test sets
train = data[1000:]
test = data[:1000]

X = train.drop(columns=['Y'])
y = train['Y']
X = sm.add_constant(X)

X_test = test.drop(columns=['Y'])
y_test = test['Y']
X_test = sm.add_constant(X_test)

In [3]:
model = sm.GLM(y, X, family=sm.families.Binomial())
result = model.fit()
#result.summary()

y_pred_prob = result.predict(X_test)
threshold = 0.25
y_pred_label = (y_pred_prob > threshold).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_label)
auc = roc_auc_score(y_test, y_pred_prob)

print("Confusion Matrix:")
print(conf_matrix)
print("AUC:", auc)

Confusion Matrix:
[[919  22]
 [ 48  11]]
AUC: 0.7407464111385291


In [5]:
def computeAIC(feature_set):
    model = sm.GLM(y, X[list(feature_set)], family=sm.families.Binomial())
    result = model.fit()
    AIC = result.aic
    return {"model":result, "AIC":AIC}

def computeBIC(feature_set):
    model = sm.GLM(y, X[list(feature_set)], family=sm.families.Binomial())
    result = model.fit()
    BIC = result.aic + len(feature_set)*(np.log(len(y))-2)
    return {"model":result, "BIC":BIC}

def AICforward(features):
    remaining_features = [p for p in X.columns if p not in features]

    results = []
    
    for p in remaining_features:
        results.append(computeAIC(features+[p]))
    
    models = pd.DataFrame(results)
    best_model = models.loc[models['AIC'].argmin()]
    
    return best_model

def BICforward(features):
    remaining_features = [p for p in X.columns if p not in features]

    results = []
    
    for p in remaining_features:
        results.append(computeBIC(features+[p]))
    
    models = pd.DataFrame(results)
    best_model = models.loc[models['BIC'].argmin()]
    
    return best_model

In [6]:
AIC_fwd = pd.DataFrame(columns=["AIC", "model"])
features = ['const']

best_AIC = 0

for i in range(1,len(X.columns)): 
    print(i)
    AIC = AICforward(features)
    if i==1:
        best_AIC = AIC['AIC']
    if best_AIC < AIC['AIC']:
        break
    best_AIC = AIC['AIC']
    AIC_fwd.loc[i] = AIC
    features = AIC_fwd.loc[i]["model"].model.exog_names

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [9]:
AIC_var_list = AIC_fwd.loc[17]["model"].model.exog_names
model = sm.GLM(y, X[list(AIC_var_list)], family=sm.families.Binomial())
result = model.fit()

y_pred_prob = result.predict(X_test[list(AIC_var_list)])
threshold = 0.25
y_pred_label = (y_pred_prob > threshold).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_label)
auc = roc_auc_score(y_test, y_pred_prob)

print("Confusion Matrix:")
print(conf_matrix)
print("AUC:", auc)

Confusion Matrix:
[[925  16]
 [ 51   8]]
AUC: 0.7353338496730848


In [11]:
len(AIC_var_list)

18

In [12]:
BIC_fwd = pd.DataFrame(columns=["BIC", "model"])
features = ['const']

best_BIC = 0

for i in range(1,len(X.columns)): 
    print(i)
    BIC = BICforward(features)
    if i==1:
        best_BIC = BIC['BIC']
    if best_BIC < BIC['BIC']:
        break
    best_BIC = BIC['BIC']
    BIC_fwd.loc[i] = BIC
    features = BIC_fwd.loc[i]["model"].model.exog_names

1
2
3
4
5
6
7


In [14]:
BIC_var_list = BIC_fwd.loc[6]["model"].model.exog_names
model = sm.GLM(y, X[list(BIC_var_list)], family=sm.families.Binomial())
result = model.fit()

y_pred_prob = result.predict(X_test[list(BIC_var_list)])
threshold = 0.25
y_pred_label = (y_pred_prob > threshold).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_label)
auc = roc_auc_score(y_test, y_pred_prob)

print("Confusion Matrix:")
print(conf_matrix)
print("AUC:", auc)

Confusion Matrix:
[[933   8]
 [ 58   1]]
AUC: 0.7414398674327707


In [15]:
features

['const', 'PPERSAUT', 'MOPLLAAG', 'PBRAND', 'APLEZIER', 'MRELGE', 'AWALAND']

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

X = train.drop(columns=['Y'])
y = train['Y']

X_test = test.drop(columns=['Y'])
y_test = test['Y']

sc = StandardScaler()
sc.fit(X)
sc.scale_ = np.std(X, axis=0, ddof=1).to_list()
newX = sc.transform(X)
newX_test = sc.transform(X_test)

newy = y.cat.codes

In [25]:
cost = 1/(newX.shape[0] * 0.004)
clf = LogisticRegression(penalty='l1', C=cost, solver='liblinear')
clf.fit(newX, newy)

LogisticRegression(C=0.05184570717544587, penalty='l1', solver='liblinear')

In [26]:
np.count_nonzero(clf.coef_)

27

In [27]:
y_pred_prob = clf.predict_proba(newX_test)[:,1]
threshold = 0.25
y_pred_label = (y_pred_prob > threshold).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_label)
auc = roc_auc_score(y_test, y_pred_prob)

print("Confusion Matrix:")
print(conf_matrix)
print("AUC:", auc)

Confusion Matrix:
[[935   6]
 [ 58   1]]
AUC: 0.7461319548262757
